#!/bin/sh

# Set these paths appropriately

BIN="/home/eershova/ADWISER/website/tt/bin"
CMD="/home/eershova/ADWISER/website/tt/cmd"
LIB="/home/eershova/ADWISER/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
