#!/bin/sh

# Set these paths appropriately

BIN="/home/eershova/ADWISER/website/tt/bin"
CMD="/home/eershova/ADWISER/website/tt/cmd"
LIB="/home/eershova/ADWISER/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
