#!/bin/sh

# Set these paths appropriately

BIN="/home/eershova/ADWISER/website/tt/bin"
CMD="/home/eershova/ADWISER/website/tt/cmd"
LIB="/home/eershova/ADWISER/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/swahili-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
